DROP TABLE IF EXISTS `PROJECT_INFO`;

CREATE TABLE `PROJECT_INFO` (
	`PRO_IDN`	bigint(8)	NOT NULL,
	`PRO_CDE`	varchar2(30)	NOT NULL,
	`PRO_NM`	varchar2(50)	NOT NULL,
	`PAY_AMT`	bigint(19.2)	NOT NULL,
	`BEG_YMD`	varchar2(8)	NOT NULL,
	`FNS_YMD`	varchar2(8)	NULL,
	`RFN_YMD`	varchar2(8)	NULL,
	`ORNT`	varchar2(30)	NOT NULL,
	`CHRG_DEPT`	varchar2(30)	NOT NULL,
	`CHRG_NM`	varchar2(10)	NOT NULL,
	`NRH_TEL`	varchar2(11)	NULL,
	`USER_TEL`	varchar2(11)	NULL,
	`PRO_RISK`	varchar2(200)	NULL,
	`PRO_STAT`	varchar2(30)	NOT NULL,
	`MNG_NM`	varchar2(10)	NULL,
	`PM_NM`	varchar2(10)	NULL,
	`BSN_NM`	varchar2(10)	NULL,
	`LOD_YMD`	varchar2(8)	NULL,
	`ORG_AMT`	bigint(19.2)	NULL
);

DROP TABLE IF EXISTS `USER_INFO`;

CREATE TABLE `USER_INFO` (
	`USER_IDN`	bigint(8)	NOT NULL,
	`USER_NM`	varchar2(30)	NOT NULL,
	`USER_CLSF`	varchar2(30)	NOT NULL,
	`USER_ID`	varchar2(32)	NOT NULL,
	`PASSWORD`	varchar2(512)	NOT NULL,
	`USER_SE`	varchar2(1)	NOT NULL,
	`UNIT_IDN`	bigint(8)	NOT NULL,
	`USER_TEL`	varchar2(11)	NULL,
	`USER_MAIL`	varchar2(50)	NULL,
	`BSNS_TEL`	varchar2(11)	NULL,
	`BRFFC`	varchar2(20)	NULL,
	`DEPT`	varchar2(20)	NULL,
	`USER_TYPE`	varchar2(30)	NOT NULL
);

DROP TABLE IF EXISTS `BSNM_SHARE_ST`;

CREATE TABLE `BSNM_SHARE_ST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`CNSRTM_NM`	varchar2(30)	NOT NULL,
	`PAY_AMT`	numeric(19,2)	NOT NULL,
	`AMT_PER`	bigint(3)	NOT NULL
);

DROP TABLE IF EXISTS `JOB_ST`;

CREATE TABLE `JOB_ST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`USER_IDN`	bigint(8)	NOT NULL,
	`JOB_TIME`	numeric(2,1)	NOT NULL,
	`LOD_YMD`	varchar2(8)	NOT NULL
);

DROP TABLE IF EXISTS `PRTN_LABOR_COST`;

CREATE TABLE `PRTN_LABOR_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`USER_IDN`	bigint(8)	NOT NULL,
	`JOB_YMD`	varchar2(8)	NOT NULL,
	`UNIT_PRICE`	numeric(19,2)	NOT NULL,
	`LBCST`	numeric(19,2)	NOT NULL,
	`LBCST_SE`	varchar2(4)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `PRTN_OUTORD_COST`;

CREATE TABLE `PRTN_OUTORD_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`ENTRPS_NM`	varchar2(20)	NOT NULL,
	`QUANTITY`	varchar2(100)	NOT NULL,
	`UNIT_PRICE`	numeric(19,2)	NOT NULL,
	`OUTORD_AMT`	numeric(19,2)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `PRTN_DIRECT_COST`;

CREATE TABLE `PRTN_DIRECT_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`PURPOSE`	varchar2(30)	NOT NULL,
	`EXPENS_AMT`	numeric(19,2)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `PRTN_OVERHEAD_COST`;

CREATE TABLE `PRTN_OVERHEAD_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`PURPOSE`	varchar2(30)	NOT NULL,
	`EXPENS_AMT`	numeric(19,2)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `HNF_INPT_PLAN`;

CREATE TABLE `HNF_INPT_PLAN` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`USER_IDN`	bigint(8)	NOT NULL,
	`TCHNLGY_TY`	varchar2(30)	NOT NULL,
	`UNIT_PRICE`	bigint(19.2)	NOT NULL
);

DROP TABLE IF EXISTS `ACMSLT_OVERHEAD_COST`;

CREATE TABLE `ACMSLT_OVERHEAD_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`PURPOSE`	varchar2(30)	NOT NULL,
	`EXPENS_AMT`	numeric(19,2)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `ACMSLT_DIRECT_COST`;

CREATE TABLE `ACMSLT_DIRECT_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`PURPOSE`	varchar2(30)	NOT NULL,
	`EXPENS_AMT`	numeric(19,2)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `ACMSLT_OUTORD_COST`;

CREATE TABLE `ACMSLT_OUTORD_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`ENTRPS_NM`	varchar2(20)	NOT NULL,
	`QUANTITY`	varchar2(100)	NOT NULL,
	`UNIT_PRICE`	numeric(19,2)	NOT NULL,
	`OUTORD_AMT`	numeric(19,2)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `ACMSLT_LABOR_COST`;

CREATE TABLE `ACMSLT_LABOR_COST` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`USER_IDN`	bigint(8)	NOT NULL,
	`JOB_YMD`	varchar2(8)	NOT NULL,
	`UNIT_PRICE`	numeric(19,2)	NOT NULL,
	`LBCST`	numeric(19,2)	NOT NULL,
	`LBCST_SE`	varchar2(4)	NOT NULL,
	`REMARK`	varchar2(50)	NULL
);

DROP TABLE IF EXISTS `UNIT_PRICE`;

CREATE TABLE `UNIT_PRICE` (
	`UNIT_IDN`	bigint(8)	NOT NULL,
	`TCHNLGY_GRAD`	varchar2(30)	NOT NULL,
	`UNIT_PRICE`	numeric(19,2)	NOT NULL,
	`STDR_YMD`	varchar2(8)	NOT NULL,
	`REMARK`	varchar2(50)	NULL,
	`USER_CLSF`	varchar2(30)	NOT NULL
);

DROP TABLE IF EXISTS `GITT_DOMN`;

CREATE TABLE `GITT_DOMN` (
	`DOMN_ID`	varchar2(32)	NOT NULL,
	`DOMN_NM`	varchar2(128)	NOT NULL
);

DROP TABLE IF EXISTS `GITT_DOMN_CODE`;

CREATE TABLE `GITT_DOMN_CODE` (
	`DOMN_ID`	varchar2(32)	NOT NULL,
	`CODE_ID`	varchar2(32)	NOT NULL,
	`CODE_NM`	varchar2(128)	NOT NULL,
	`USE_AT`	varchar2(1)	NOT NULL
);

DROP TABLE IF EXISTS `GITT_FILE_INFO`;

CREATE TABLE `GITT_FILE_INFO` (
	`SHT_IDN`	bigint	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL,
	`FILE_NO`	bigint	NOT NULL,
	`FILE_TYPE`	varchar(10)	NOT NULL
);

DROP TABLE IF EXISTS `GITT_FILE`;

CREATE TABLE `GITT_FILE` (
	`FILE_NO`	bigint	NOT NULL,
	`FILE_STRE_COURS`	varchar2(2048)	NULL,
	`STRE_FILE_NM`	varchar2(256)	NULL,
	`ORG_FILE_NM`	varchar2(256)	NULL,
	`FILE_EXTSN`	varchar2(16)	NULL,
	`FILE_SIZE`	bigint	NULL
);

DROP TABLE IF EXISTS `EXPENSE_RATIO`;

CREATE TABLE `EXPENSE_RATIO` (
	`SHT_IDN`	bigint	NOT NULL,
	`EXP_RAT`	numeric(8.2)	NOT NULL,
	`STDR_YMD`	varchar(8)	NOT NULL
);

DROP TABLE IF EXISTS `GITT_PROCESS`;

CREATE TABLE `GITT_PROCESS` (
	`SHT_IDN`	bigint(8)	NOT NULL,
	`PROCESS`	varchar(32)	NOT NULL,
	`JOB_TIME`	numeric(4,1)	NOT NULL,
	`PRO_IDN`	bigint(8)	NOT NULL
);

ALTER TABLE `PROJECT_INFO` ADD CONSTRAINT `PK_PROJECT_INFO` PRIMARY KEY (
	`PRO_IDN`
);

ALTER TABLE `USER_INFO` ADD CONSTRAINT `PK_USER_INFO` PRIMARY KEY (
	`USER_IDN`
);

ALTER TABLE `BSNM_SHARE_ST` ADD CONSTRAINT `PK_BSNM_SHARE_ST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `JOB_ST` ADD CONSTRAINT `PK_JOB_ST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `PRTN_LABOR_COST` ADD CONSTRAINT `PK_PRTN_LABOR_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `PRTN_OUTORD_COST` ADD CONSTRAINT `PK_PRTN_OUTORD_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `PRTN_DIRECT_COST` ADD CONSTRAINT `PK_PRTN_DIRECT_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `PRTN_OVERHEAD_COST` ADD CONSTRAINT `PK_PRTN_OVERHEAD_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `HNF_INPT_PLAN` ADD CONSTRAINT `PK_HNF_INPT_PLAN` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `ACMSLT_OVERHEAD_COST` ADD CONSTRAINT `PK_ACMSLT_OVERHEAD_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `ACMSLT_DIRECT_COST` ADD CONSTRAINT `PK_ACMSLT_DIRECT_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `ACMSLT_OUTORD_COST` ADD CONSTRAINT `PK_ACMSLT_OUTORD_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `ACMSLT_LABOR_COST` ADD CONSTRAINT `PK_ACMSLT_LABOR_COST` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `UNIT_PRICE` ADD CONSTRAINT `PK_UNIT_PRICE` PRIMARY KEY (
	`UNIT_IDN`
);

ALTER TABLE `GITT_DOMN` ADD CONSTRAINT `PK_GITT_DOMN` PRIMARY KEY (
	`DOMN_ID`
);

ALTER TABLE `GITT_DOMN_CODE` ADD CONSTRAINT `PK_GITT_DOMN_CODE` PRIMARY KEY (
	`DOMN_ID`
);

ALTER TABLE `GITT_FILE_INFO` ADD CONSTRAINT `PK_GITT_FILE_INFO` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `GITT_FILE` ADD CONSTRAINT `PK_GITT_FILE` PRIMARY KEY (
	`FILE_NO`
);

ALTER TABLE `EXPENSE_RATIO` ADD CONSTRAINT `PK_EXPENSE_RATIO` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `GITT_PROCESS` ADD CONSTRAINT `PK_GITT_PROCESS` PRIMARY KEY (
	`SHT_IDN`
);

ALTER TABLE `USER_INFO` ADD CONSTRAINT `FK_UNIT_PRICE_TO_USER_INFO_1` FOREIGN KEY (
	`UNIT_IDN`
)
REFERENCES `UNIT_PRICE` (
	`UNIT_IDN`
);

ALTER TABLE `BSNM_SHARE_ST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_BSNM_SHARE_ST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `JOB_ST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_JOB_ST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `JOB_ST` ADD CONSTRAINT `FK_USER_INFO_TO_JOB_ST_1` FOREIGN KEY (
	`USER_IDN`
)
REFERENCES `USER_INFO` (
	`USER_IDN`
);

ALTER TABLE `PRTN_LABOR_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_PRTN_LABOR_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `PRTN_LABOR_COST` ADD CONSTRAINT `FK_USER_INFO_TO_PRTN_LABOR_COST_1` FOREIGN KEY (
	`USER_IDN`
)
REFERENCES `USER_INFO` (
	`USER_IDN`
);

ALTER TABLE `PRTN_OUTORD_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_PRTN_OUTORD_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `PRTN_DIRECT_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_PRTN_DIRECT_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `PRTN_OVERHEAD_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_PRTN_OVERHEAD_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `HNF_INPT_PLAN` ADD CONSTRAINT `FK_PROJECT_INFO_TO_HNF_INPT_PLAN_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `HNF_INPT_PLAN` ADD CONSTRAINT `FK_USER_INFO_TO_HNF_INPT_PLAN_1` FOREIGN KEY (
	`USER_IDN`
)
REFERENCES `USER_INFO` (
	`USER_IDN`
);

ALTER TABLE `ACMSLT_OVERHEAD_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_ACMSLT_OVERHEAD_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `ACMSLT_DIRECT_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_ACMSLT_DIRECT_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `ACMSLT_OUTORD_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_ACMSLT_OUTORD_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `ACMSLT_LABOR_COST` ADD CONSTRAINT `FK_PROJECT_INFO_TO_ACMSLT_LABOR_COST_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `ACMSLT_LABOR_COST` ADD CONSTRAINT `FK_USER_INFO_TO_ACMSLT_LABOR_COST_1` FOREIGN KEY (
	`USER_IDN`
)
REFERENCES `USER_INFO` (
	`USER_IDN`
);

ALTER TABLE `GITT_DOMN_CODE` ADD CONSTRAINT `FK_GITT_DOMN_TO_GITT_DOMN_CODE_1` FOREIGN KEY (
	`DOMN_ID`
)
REFERENCES `GITT_DOMN` (
	`DOMN_ID`
);

ALTER TABLE `GITT_FILE_INFO` ADD CONSTRAINT `FK_PROJECT_INFO_TO_GITT_FILE_INFO_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

ALTER TABLE `GITT_FILE_INFO` ADD CONSTRAINT `FK_GITT_FILE_TO_GITT_FILE_INFO_1` FOREIGN KEY (
	`FILE_NO`
)
REFERENCES `GITT_FILE` (
	`FILE_NO`
);

ALTER TABLE `GITT_PROCESS` ADD CONSTRAINT `FK_PROJECT_INFO_TO_GITT_PROCESS_1` FOREIGN KEY (
	`PRO_IDN`
)
REFERENCES `PROJECT_INFO` (
	`PRO_IDN`
);

