USE [EmployeeCaseStudy]
GO
SET IDENTITY_INSERT [dbo].[Employee] ON 

INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (1, N'Stein                         ', N'Nidprxmvtyjnat               ', N'D', N'122-08-9952', N'Ap #461-7976 Enim. Street               ', N'Rutland         ', N'VT', N'90400', N'1-796-415-8913', 5, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (2, N'Eflin                         ', N'Ysgphbplbhoksy               ', N'G', N'325-09-9913', N'2385 Cum Ave                            ', N'Cedar Rapids    ', N'IA', N'75214', N'1-995-495-3419', 6, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (3, N'Quint                         ', N'Ysoawvtycuwv                 ', N'O', N'590-10-9874', N'P.O. Box 148, 8247 Donec Street         ', N'Kaneohe         ', N'HI', N'97807', N'1-789-348-2880', 6, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (4, N'Chen                          ', N'Mju                          ', N'U', N'746-11-9835', N'285-7941 Tellus Avenue                  ', N'Davenport       ', N'IA', N'67467', N'1-737-705-4111', 6, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (5, N'Olphant                       ', N'Tqbigir                      ', N'B', N'978-12-9796', N'191-3212 Enim, St.                      ', N'Erie            ', N'PA', N'55214', N'1-503-256-1715', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (6, N'Anderson                      ', N'Dreaxjktgvnhye               ', N'E', N'244-13-9757', N'9254 Morbi St.                          ', N'Pike Creek      ', N'DE', N'53494', N'1-588-740-3153', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (7, N'Makai                         ', N'Lnudwgnbtoyvix               ', N'U', N'460-14-9718', N'991-2772 Eu, Ave                        ', N'Lewiston        ', N'ME', N'72134', N'1-380-808-1149', 7, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (8, N'Yeong                         ', N'Gttwynjpwb                   ', N'T', N'662-15-9679', N'7914 Turpis Street                      ', N'Madison         ', N'WI', N'97804', N'1-568-466-7462', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (9, N'Kahrmann                      ', N'Svjampio                     ', N'J', N'974-16-9640', N'P.O. Box 396, 6323 In Rd.               ', N'Juneau          ', N'AK', N'99742', N'1-742-467-1456', 7, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (10, N'Wolfmule                      ', N'Uusfynrfejusqx               ', N'S', N'283-17-9601', N'5438 Malesuada St.                      ', N'Las Vegas       ', N'NV', N'52031', N'1-967-295-3855', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (11, N'Infante                       ', N'Dxnw                         ', N'N', N'642-18-9562', N'Ap #631-3376 Pharetra St.               ', N'Clarksville     ', N'TN', N'15557', N'1-169-646-6099', 7, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (12, N'Unaklet                       ', N'Xdelgxxbfomgie               ', N'E', N'018-19-9523', N'P.O. Box 589, 3701 Ipsum. Av.           ', N'Owensboro       ', N'KY', N'31716', N'1-652-212-9047', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (13, N'Gohan                         ', N'Icwaxehqf                    ', N'W', N'327-20-9484', N'P.O. Box 181, 6251 Dolor. Rd.           ', N'Burlington      ', N'VT', N'10868', N'1-624-730-0705', 8, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (14, N'Stein                         ', N'Qfgakkjblwfbkb               ', N'G', N'749-21-9445', N'P.O. Box 410, 6131 Dictum Av.           ', N'Casper          ', N'WY', N'61341', N'1-655-153-3387', 8, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (15, N'Eflin                         ', N'Qqlbhirg                     ', N'L', N'045-22-9406', N'P.O. Box 356, 4819 Nulla Avenue         ', N'Baton Rouge     ', N'LA', N'17617', N'1-230-688-3875', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (16, N'Quint                         ', N'Ymdomf                       ', N'D', N'357-23-9367', N'Ap #930-1821 Diam. Ave                  ', N'Reno            ', N'NV', N'74699', N'1-285-608-7561', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (17, N'Chen                          ', N'Jdjoemmumy                   ', N'J', N'716-24-9328', N'P.O. Box 196, 6595 Duis St.             ', N'Columbia        ', N'MO', N'29870', N'1-430-274-1573', 8, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (18, N'Olphant                       ', N'Pij                          ', N'J', N'215-25-9289', N'9214 Nec Av.                            ', N'Lawton          ', N'OK', N'65920', N'1-296-158-0358', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (19, N'Anderson                      ', N'Hvxlqig                      ', N'X', N'541-26-9250', N'189-9186 At, St.                        ', N'Houston         ', N'TX', N'37487', N'1-979-616-4074', 9, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[Employee] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (20, N'Makai                         ', N'Slhcsdtsrqcmzo               ', N'H', N'007-27-9211', N'914-6219 Gravida St.                    ', N'Cleveland       ', N'OH', N'19687', N'1-421-147-3597', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
GO
SET IDENTITY_INSERT [dbo].[Employee] OFF
SET IDENTITY_INSERT [dbo].[EmployeeHeap] ON 

INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (1, N'Stein                         ', N'Nidprxmvtyjnat               ', N'D', N'122-08-9952', N'Ap #461-7976 Enim. Street               ', N'Rutland         ', N'VT', N'90400', N'1-796-415-8913', 5, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (2, N'Eflin                         ', N'Ysgphbplbhoksy               ', N'G', N'325-09-9913', N'2385 Cum Ave                            ', N'Cedar Rapids    ', N'IA', N'75214', N'1-995-495-3419', 6, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (3, N'Quint                         ', N'Ysoawvtycuwv                 ', N'O', N'590-10-9874', N'P.O. Box 148, 8247 Donec Street         ', N'Kaneohe         ', N'HI', N'97807', N'1-789-348-2880', 6, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (4, N'Chen                          ', N'Mju                          ', N'U', N'746-11-9835', N'285-7941 Tellus Avenue                  ', N'Davenport       ', N'IA', N'67467', N'1-737-705-4111', 6, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (5, N'Olphant                       ', N'Tqbigir                      ', N'B', N'978-12-9796', N'191-3212 Enim, St.                      ', N'Erie            ', N'PA', N'55214', N'1-503-256-1715', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (6, N'Anderson                      ', N'Dreaxjktgvnhye               ', N'E', N'244-13-9757', N'9254 Morbi St.                          ', N'Pike Creek      ', N'DE', N'53494', N'1-588-740-3153', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (7, N'Makai                         ', N'Lnudwgnbtoyvix               ', N'U', N'460-14-9718', N'991-2772 Eu, Ave                        ', N'Lewiston        ', N'ME', N'72134', N'1-380-808-1149', 7, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (8, N'Yeong                         ', N'Gttwynjpwb                   ', N'T', N'662-15-9679', N'7914 Turpis Street                      ', N'Madison         ', N'WI', N'97804', N'1-568-466-7462', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (9, N'Kahrmann                      ', N'Svjampio                     ', N'J', N'974-16-9640', N'P.O. Box 396, 6323 In Rd.               ', N'Juneau          ', N'AK', N'99742', N'1-742-467-1456', 7, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (10, N'Wolfmule                      ', N'Uusfynrfejusqx               ', N'S', N'283-17-9601', N'5438 Malesuada St.                      ', N'Las Vegas       ', N'NV', N'52031', N'1-967-295-3855', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (11, N'Infante                       ', N'Dxnw                         ', N'N', N'642-18-9562', N'Ap #631-3376 Pharetra St.               ', N'Clarksville     ', N'TN', N'15557', N'1-169-646-6099', 7, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (12, N'Unaklet                       ', N'Xdelgxxbfomgie               ', N'E', N'018-19-9523', N'P.O. Box 589, 3701 Ipsum. Av.           ', N'Owensboro       ', N'KY', N'31716', N'1-652-212-9047', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (13, N'Gohan                         ', N'Icwaxehqf                    ', N'W', N'327-20-9484', N'P.O. Box 181, 6251 Dolor. Rd.           ', N'Burlington      ', N'VT', N'10868', N'1-624-730-0705', 8, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (14, N'Stein                         ', N'Qfgakkjblwfbkb               ', N'G', N'749-21-9445', N'P.O. Box 410, 6131 Dictum Av.           ', N'Casper          ', N'WY', N'61341', N'1-655-153-3387', 8, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (15, N'Eflin                         ', N'Qqlbhirg                     ', N'L', N'045-22-9406', N'P.O. Box 356, 4819 Nulla Avenue         ', N'Baton Rouge     ', N'LA', N'17617', N'1-230-688-3875', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (16, N'Quint                         ', N'Ymdomf                       ', N'D', N'357-23-9367', N'Ap #930-1821 Diam. Ave                  ', N'Reno            ', N'NV', N'74699', N'1-285-608-7561', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (17, N'Chen                          ', N'Jdjoemmumy                   ', N'J', N'716-24-9328', N'P.O. Box 196, 6595 Duis St.             ', N'Columbia        ', N'MO', N'29870', N'1-430-274-1573', 8, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (18, N'Olphant                       ', N'Pij                          ', N'J', N'215-25-9289', N'9214 Nec Av.                            ', N'Lawton          ', N'OK', N'65920', N'1-296-158-0358', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (19, N'Anderson                      ', N'Hvxlqig                      ', N'X', N'541-26-9250', N'189-9186 At, St.                        ', N'Houston         ', N'TX', N'37487', N'1-979-616-4074', 9, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
INSERT [dbo].[EmployeeHeap] ([EmployeeID], [LastName], [FirstName], [MiddleInitial], [SSN], [Address], [City], [State], [Zip], [Phone], [Status], [Description]) VALUES (20, N'Makai                         ', N'Slhcsdtsrqcmzo               ', N'H', N'007-27-9211', N'914-6219 Gravida St.                    ', N'Cleveland       ', N'OH', N'19687', N'1-421-147-3597', 1, N'This is sample data for the Employee Case Study.                                                                                                                                   ')
GO
SET IDENTITY_INSERT [dbo].[EmployeeHeap] OFF
