USE employeeCaseStudy
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [employeeCaseStudy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [employeeCaseStudy] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET ARITHABORT OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [employeeCaseStudy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [employeeCaseStudy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET  DISABLE_BROKER 
GO
ALTER DATABASE [employeeCaseStudy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [employeeCaseStudy] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [employeeCaseStudy] SET  MULTI_USER 
GO
ALTER DATABASE [employeeCaseStudy] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [employeeCaseStudy] SET DB_CHAINING OFF 
GO
ALTER DATABASE [employeeCaseStudy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [employeeCaseStudy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [employeeCaseStudy] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'employeeCaseStudy', N'ON'
GO
ALTER DATABASE [employeeCaseStudy] SET QUERY_STORE = OFF
GO
USE [employeeCaseStudy]
GO
ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO
USE [employeeCaseStudy]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 2020-09-29 5:22:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nchar](30) NOT NULL,
	[FirstName] [nchar](29) NOT NULL,
	[MiddleInitial] [nchar](1) NULL,
	[SSN] [char](11) NOT NULL,
	[Address] [char](40) NOT NULL,
	[City] [char](16) NOT NULL,
	[State] [char](2) NOT NULL,
	[Zip] [char](5) NOT NULL,
	[Phone] [char](14) NOT NULL,
	[Status] [tinyint] NOT NULL,
	[Description] [char](179) NOT NULL,
 CONSTRAINT [EmployeePK] PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [SSNUK] UNIQUE NONCLUSTERED 
(
	[SSN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmployeeHeap]    Script Date: 2020-09-29 5:23:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmployeeHeap](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nchar](30) NOT NULL,
	[FirstName] [nchar](29) NOT NULL,
	[MiddleInitial] [nchar](1) NULL,
	[SSN] [char](11) NOT NULL,
	[Address] [char](40) NOT NULL,
	[City] [char](16) NOT NULL,
	[State] [char](2) NOT NULL,
	[Zip] [char](5) NOT NULL,
	[Phone] [char](14) NOT NULL,
	[Status] [tinyint] NOT NULL,
	[Description] [char](179) NOT NULL,
 CONSTRAINT [EmployeeHeapPK] PRIMARY KEY NONCLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [SSNHeapUK] UNIQUE NONCLUSTERED 
(
	[SSN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Employee] ADD  DEFAULT ('This is sample data for the Employee Case Study.') FOR [Description]
GO
ALTER TABLE [dbo].[EmployeeHeap] ADD  DEFAULT ('This is sample data for the Employee Case Study.') FOR [Description]
GO
USE [master]
GO
ALTER DATABASE [employeeCaseStudy] SET  READ_WRITE 
GO
