on:
  workflow_dispatch:

jobs:
  env:
    CI: 1
    DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  publish-to-docker:
    runs-on: ubuntu-latest
    steps:
      - run: sh build.sh ${{ github.event.inputs.dockerTag }}
