-- https://www.postgresql.org/docs/9.5/datatype.html
create table types (
	numeric_integer_smallint smallint,
	numeric_integer_integer integer,
	numeric_integer_bigint bigint,
	numeric_integer_decimal decimal,
	numeric_arbitrary_numeric numeric,
	numeric_floating_real real,
	numeric_floating_double_precision double precision,
	numeric_serial_smallserial smallserial,
	numeric_serial_serial serial,
	numeric_serial_bigserial bigserial,
	monetary_money money,
	character_character_varying character varying,
	character_character character,
	character_varchar varchar,
	character_char char,
	character_text text,
	binary_bytea bytea,
	datetime_timestamp timestamp,
	datetime_timestamp_without_time_zone timestamp without time zone,
	datetime_timestamp_with_time_zone timestamp with time zone,
	datetime_timestamptz timestamptz,
	datetime_date date,
	datetime_time time,
	datetime_time_without_time_zone time without time zone,
	datetime_time_with_time_zone time with time zone,
	datetime_interval interval,
	datetime_interval_year interval year,
	datetime_interval_month interval month,
	datetime_interval_day interval day,
	datetime_interval_hour interval hour,
	datetime_interval_minute interval minute,
	datetime_interval_second interval second,
	datetime_interval_year_to_month interval year to month,
	datetime_interval_day_to_hour interval day to hour,
	datetime_interval_day_to_minute interval day to minute,
	datetime_interval_day_to_second interval day to second,
	datetime_interval_hour_to_minute interval hour to minute,
	datetime_interval_hour_to_second interval hour to second,
	datetime_interval_minute_to_second interval minute to second,
	boolean_boolean boolean,
	geometric_point point,
	geometric_line line,
	geometric_lseg lseg,
	geometric_box box,
	geometric_path path,
	geometric_polygon polygon,
	geometric_circle circle,
	network_cidr cidr,
	network_inet inet,
	network_macaddr macaddr,
	network_macaddr8 macaddr8,
	bitstring_bit bit,
	bitstring_bit_varying bit varying,
	textsearch_tsvector tsvector,
	textsearch_tsquery tsquery,
	uuid_uuid uuid,
	xml_xml xml,
	json_json json,
	json_jsonb jsonb,
	range_int4range int4range,
	range_int8range int8range,
	range_numrange numrange,
	range_tsrange tsrange,
	range_tstzrange tstzrange,
	range_daterange daterange,
	other_pg_lsn pg_lsn,
	other_txid_snapshot txid_snapshot
)

-- https://www.postgresql.org/docs/9.1/arrays.html
create table types_array1 (
	numeric_integer_smallint smallint[],
	numeric_integer_integer integer[],
	numeric_integer_bigint bigint[],
	numeric_integer_decimal decimal[],
	numeric_arbitrary_numeric numeric[],
	numeric_floating_real real[],
	numeric_floating_double_precision double precision[],
	monetary_money money[],
	character_character_varying character varying[],
	character_character character[],
	character_varchar varchar[],
	character_char char[],
	character_text text[],
	binary_bytea bytea[],
	datetime_timestamp timestamp[],
	datetime_timestamp_without_time_zone timestamp without time zone[],
	datetime_timestamp_with_time_zone timestamp with time zone[],
	datetime_timestamptz timestamptz[],
	datetime_date date[],
	datetime_time time[],
	datetime_time_without_time_zone time without time zone[],
	datetime_time_with_time_zone time with time zone[],
	datetime_interval interval[],
	datetime_interval_year interval year[],
	datetime_interval_month interval month[],
	datetime_interval_day interval day[],
	datetime_interval_hour interval hour[],
	datetime_interval_minute interval minute[],
	datetime_interval_second interval second[],
	datetime_interval_year_to_month interval year to month[],
	datetime_interval_day_to_hour interval day to hour[],
	datetime_interval_day_to_minute interval day to minute[],
	datetime_interval_day_to_second interval day to second[],
	datetime_interval_hour_to_minute interval hour to minute[],
	datetime_interval_hour_to_second interval hour to second[],
	datetime_interval_minute_to_second interval minute to second[],
	boolean_boolean boolean[],
	geometric_point point[],
	geometric_line line[],
	geometric_lseg lseg[],
	geometric_box box[],
	geometric_path path[],
	geometric_polygon polygon[],
	geometric_circle circle[],
	network_cidr cidr[],
	network_inet inet[],
	network_macaddr macaddr[],
	network_macaddr8 macaddr8[],
	bitstring_bit bit[],
	bitstring_bit_varying bit varying[],
	textsearch_tsvector tsvector[],
	textsearch_tsquery tsquery[],
	uuid_uuid uuid[],
	xml_xml xml[],
	json_json json[],
	json_jsonb jsonb[],
	range_int4range int4range[],
	range_int8range int8range[],
	range_numrange numrange[],
	range_tsrange tsrange[],
	range_tstzrange tstzrange[],
	range_daterange daterange[],
	other_pg_lsn pg_lsn[],
	other_txid_snapshot txid_snapshot[]
)
